baseURL: ""
languageCode: "he"
title: DataBuzz
theme: PaperMod

menu:
  main:
    - identifier: posts
      name: פוסטים
      url: /Posts/
      weight: 1
    
    - identifier: aboutme
      name: הסיפור שלי
      url: /other/aboutme/
      weight: 2