baseURL: ""
languageCode: "he"
languageName: "Hebrew"
isoCode: "he"
weight: 1
rtl: true
title: DataBuzz
theme: PaperMod

menu:
  main:
    - identifier: posts
      name: פוסטים
      url: /Posts/
      weight: 1
    
    - identifier: aboutme
      name: הסיפור שלי
      url: /other/aboutme/
      weight: 2