baseURL: "DataBuzz"
languageCode: "he"
title: DataBuzz
theme: PaperMod

menu:
  main:
    - identifier: Posts
      name: Posts
      url: /Posts/
      weight: 1
    
    - identifier: About_me
      name: About Me
      url: /aboutme/
      weight: 2
    
